### ISSUE TITLE
error when executing

### ISSUE THREAD

**Issue by viliusl** [wix/okidoc#5]
node version 6

```bash
(master *)$ node_modules/.bin/okidoc
node_modules/okidoc/bin/okidoc.js:30
      );
      ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

afaik it only supports node@8 and upwards - maybe add this to `engines` directive in package.json ?

**Comment by bodia-uz** [comment]
Engine added in [v1.0.2](https://github.com/wix/okidoc/releases/tag/v1.0.2)
