### ISSUE TITLE
better feedback for no args?

### ISSUE THREAD

**Issue by viliusl** [wix/okidoc#6]
```bash
(master *)$ node_modules/.bin/okidoc
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Function.Utils.getStringFromFile (/node_modules/yamljs/lib/Utils.js:284:19)
    at Function.Yaml.parseFile (/node_modules/yamljs/lib/Yaml.js:46:21)
    at Function.Yaml.load (/node_modules/yamljs/lib/Yaml.js:78:17)
    at Object.<anonymous> (/node_modules/okidoc/bin/okidoc.js:17:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

not a biggie, but would be nice to get some nicer feedback:)

**Comment by bodia-uz** [comment]
Fixed in [v1.0.2](https://github.com/wix/okidoc/releases/tag/v1.0.2)
